homeassistant:
  unit_system: metric
  time_zone: America/Vancouver

# Discover some devices automatically
# discovery:

# Checks for available updates
updater:

# Enables the frontend
frontend:

# Track the sun
# sun:

# Allows you to issue voice commands from the frontend
conversation:

# View all events in a logbook
logbook:

# Show links to resources in log and frontend
# introduction:

# Enables support for tracking state changes over time.
history:

http:           !include authentication.yaml
nest:           !include nest_authentication.yaml
mqtt:           !include mqtt.yaml
zone:           !include zones.yaml
device_tracker: !include devices/device_tracker.yaml
climate:        !include devices/thermostat.yaml
sensor:         !include sensors.yaml
script:         !include scripts.yaml
notify:         !include devices/notification.yaml
automation:     !include automation.yaml
