alias: "(Afterwork) Leaving Surrey Central Station"
trigger:
- platform: zone
  event: leave
  zone: zone.surrey_central_station
  entity_id: device_tracker.andy_iphone
condition: 
- condition: time
  after: '17:00'
  before: '20:00'
  weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
action:
  service: script.coming_home  
